# Site settings
title: ASN INFO
email: admin@aridjaya.com
description: >
  A collection of high-quality HD, Full HD, and 4K wallpapers featuring nature landscapes, mountains, forests, beaches, sunsets, city views, and aesthetic designs.

url: "https://asninfoh.github.io"
baseurl: "/"

timezone: Asia/Jakarta

future: false
logo: images/logo.jpg
default-image: logo.jpg

built-by: ASN INFO

copyright:
  name: ASN INFO
  link: "https://asninfoh.github.io"

markdown: kramdown
permalink: /:title/

paginate: 12
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap