# Site settings
title: ASN INFO
email: admin@aridjaya.com
description: >
  Portal informasi ASN, CPNS, PPPK, kebijakan, formasi, gaji, dan karier Aparatur Sipil Negara di Indonesia
  
url: "https://asninfoh.github.io"
baseurl: "/"

timezone: Asia/Jakarta

future: false
logo: logo.jpg
default-image: default.jpg

built-by: ASN INFO

copyright:
  name: ASN INFO
  link: "https://asninfo.id"

markdown: kramdown
permalink: /:title/

paginate: 12
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap